/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package triki2;

/**
 *
 * @author David
 */
public class Tablero extends javax.swing.JFrame {
    
    Fichas game;
     int x;
     int y;
     int w;
     
     

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pos11 = new java.awt.Label();
        pos12 = new java.awt.Label();
        pos13 = new java.awt.Label();
        pos21 = new java.awt.Label();
        pos22 = new java.awt.Label();
        pos23 = new java.awt.Label();
        pos31 = new java.awt.Label();
        pos32 = new java.awt.Label();
        pos33 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 3));

        pos11.setText("label1");
        pos11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos11MouseClicked(evt);
            }
        });
        getContentPane().add(pos11);

        pos12.setText("label4");
        pos12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos12MouseClicked(evt);
            }
        });
        getContentPane().add(pos12);

        pos13.setText("label7");
        pos13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos13MouseClicked(evt);
            }
        });
        getContentPane().add(pos13);

        pos21.setText("label2");
        pos21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos21MouseClicked(evt);
            }
        });
        getContentPane().add(pos21);

        pos22.setText("label3");
        pos22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos22MouseClicked(evt);
            }
        });
        getContentPane().add(pos22);

        pos23.setText("label5");
        pos23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos23MouseClicked(evt);
            }
        });
        getContentPane().add(pos23);

        pos31.setText("label6");
        pos31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos31MouseClicked(evt);
            }
        });
        getContentPane().add(pos31);

        pos32.setText("label8");
        pos32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos32MouseClicked(evt);
            }
        });
        getContentPane().add(pos32);

        pos33.setText("label9");
        pos33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos33MouseClicked(evt);
            }
        });
        getContentPane().add(pos33);

        jMenu1.setText("Nuevo juego");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("ganador");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pos11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos11MouseClicked
        // TODO add your handling code here:
        pos11.setText(String.valueOf(game.jugador()));
        if((game.jugador()=="X")||(game.jugador()=="O")){
            x++;
        }
        if((game.jugador()=="X")||(game.jugador()=="O")){
            y++;
        }
        
        
    }//GEN-LAST:event_pos11MouseClicked

    private void pos12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos12MouseClicked
        // TODO add your handling code here:
        pos12.setText(String.valueOf(game.jugador()));
        if((game.jugador()=="X")||(game.jugador()=="O")){
            x++;
        }
        if((game.jugador()=="X")||(game.jugador()=="O")){
            w++;
        }
        
    }//GEN-LAST:event_pos12MouseClicked

    private void pos13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos13MouseClicked
        // TODO add your handling code here:
        pos13.setText(String.valueOf(game.jugador()));
        
    }//GEN-LAST:event_pos13MouseClicked

    private void pos21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos21MouseClicked
        // TODO add your handling code here:
        pos21.setText(String.valueOf(game.jugador()));
        
    }//GEN-LAST:event_pos21MouseClicked

    private void pos22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos22MouseClicked
        // TODO add your handling code here:
        pos22.setText(String.valueOf(game.jugador()));
        
    }//GEN-LAST:event_pos22MouseClicked

    private void pos23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos23MouseClicked
        // TODO add your handling code here:
        pos23.setText(String.valueOf(game.jugador()));
        
    }//GEN-LAST:event_pos23MouseClicked

    private void pos31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos31MouseClicked
        // TODO add your handling code here:
        pos31.setText(String.valueOf(game.jugador()));
      
    }//GEN-LAST:event_pos31MouseClicked

    private void pos32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos32MouseClicked
        // TODO add your handling code here:
        pos32.setText(String.valueOf(game.jugador()));
    
    }//GEN-LAST:event_pos32MouseClicked

    private void pos33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos33MouseClicked
        // TODO add your handling code here:
        pos33.setText(String.valueOf(game.jugador()));
    }//GEN-LAST:event_pos33MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
       
        
        
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Label pos11;
    private java.awt.Label pos12;
    private java.awt.Label pos13;
    private java.awt.Label pos21;
    private java.awt.Label pos22;
    private java.awt.Label pos23;
    private java.awt.Label pos31;
    private java.awt.Label pos32;
    private java.awt.Label pos33;
    // End of variables declaration//GEN-END:variables
}
